### ISSUE TITLE
Error performing any command

### ISSUE THREAD

**Issue by danikula** [pangliang/miband-sdk-android#21]
Hello. I try to use your sdk for Mi Band 1S, firmware 4.15.12.10, HeartRate 1.3.74.64. My device is Nexus 5, android 6.0.1.

I use your sample app, connect to device and try to perform any operation, like `setUserInfo`, `getBattery`, etc,... but every time got error
```
com.zhaoxiaodan.mibanddemo E/BluetoothIO: writeCharacteristic
java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattCharacteristic android.bluetooth.BluetoothGattService.getCharacteristic(java.util.UUID)' on a null object reference
at com.zhaoxiaodan.miband.BluetoothIO.writeCharacteristic(BluetoothIO.java:70)
at com.zhaoxiaodan.miband.BluetoothIO.writeCharacteristic(BluetoothIO.java:60)
at com.zhaoxiaodan.miband.MiBand.setUserInfo(MiBand.java:275)
at com.zhaoxiaodan.mibanddemo.MainActivity$2.onItemClick(MainActivity.java:149)
at android.widget.AdapterView.performItemClick(AdapterView.java:310)
at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
at android.widget.AbsListView$3.run(AbsListView.java:3903)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by PoarryScript** [comment]
hi!
I have same problem，
do you have some idea?
